services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    ports:
      - "628:628"
    environment:
      NODE_ENV: production
      PORT: 628
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - 1panel-network
    restart: always

networks:
  1panel-network:
    external: true
